name: Deploy to AWS

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: Deploy to DEV
      if: github.event_name == 'pull_request' && github.base_ref == 'develop'
      run: echo "DEPLOY -> DEV"

    - name: Deploy to STAGE
      if: github.event_name == 'pull_request' && github.base_ref == 'main'
      run: echo "DEPLOY -> STAGE"
    - name: Deploy to PROD
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: echo "DEPLOY -> PROD"

